### ISSUE TITLE
No troughput from Docker0 interface

### ISSUE THREAD

**Issue by juergschwarz** [gsxryan/storj_telegraf_mon#14]
Hi all.

I just got my grafana dashboard with storj_telegraf_mon up and running. But as you can see on the pic i dont have any data points on the docker0 interface.

Here comes my telegraf.conf

[[inputs.docker]]

   endpoint = "unix:///var/run/docker.sock"

   gather_services = false

   container_names = []

   container_name_include = []
   container_name_exclude = []

   timeout = "5s"

   perdevice = true

   total = false

   docker_label_include = []
   docker_label_exclude = []

![Bildschirmfoto von 2019-07-27 12-13-09](https://user-images.githubusercontent.com/18343961/61993165-f3ce1480-b067-11e9-8607-fc1b71544765.png)

**Comment by juergschwarz** [comment]
Ok checked it

[[inputs.net]]
  interfaces = ["docker0"]

made the job

**Comment by gsxryan** [comment]
Nice work!  I had thought that [[inputs.net]] should grab all interfaces, but it looks like you can also specify.
