### ISSUE TITLE
Throughput of Docker0 Interface

### ISSUE THREAD

**Issue by TheChrisTech** [gsxryan/storj_telegraf_mon#19]
So I'm running Docker on Windows Server 2016, but am not running my telegraf in a docker instance. I'm trying to get the docker network stats working, but it's not collecting any datapoints, even when checking with the '--test' flag.
In my telegraf.conf, I have:
```
[[inputs.net]]
## NIC Traffic Monitor
interfaces = ["docker0"]
```
Which seems like it should work, but it doesn't. Everything else is working as expected, except for this. Any ideas?

**Comment by TheChrisTech** [comment]
May have resolved this, but not sure of it's accuracy. Ended up needing to import the following in my telegraf.conf:
```
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Hyper-V Virtual Network Adapter"
    Counters = [
      "Bytes Received/sec",
      "Bytes Sent/sec",
      "Read Bytes/sec"
    ]
    Instances = ["*"]
    Measurement = "Hyper-V_Virtual_Network_Adapter"
```
This allowed me to modify the grafana chart to output these captured values instead. I'll report back once I confirm these values are legit (Both received and sent are the same values atm).

**Comment by gsxryan** [comment]
Nice job!  I was about to say the windows inputs would likely be different in windows host telegraf.  You won't be able to capture docker0, as your outside the container, and a level removed from it.  You'll need to capture the windows virtual adapter, as it looks like you've done.

All who've tested it so far have been on some kind of linux system as far as i know.  Thanks for grabbing the windows docker details.  You're welcome to commit to the readme, or i'll grab it once you verify it works.
