### ISSUE TITLE
Storage stats

### ISSUE THREAD

**Issue by ghost** [gsxryan/storj_telegraf_mon#24]
Instead of:
https://github.com/gsxryan/storj_telegraf_mon/blob/a5d077f856bf8898528bce9ac5c9d58dc41a23cf/folder_size.sh#L16

Why not query the sqlite database or dashboard api?

**Comment by gsxryan** [comment]
Calling on @JeromeGillard for this one.

At the time the SQLlite database was not documented.  And, the dashboard API was unavailable.  This could go under #21 or #3

**Comment by JeromeGillard** [comment]
Addressed in PR #25.
